### ISSUE TITLE
TypeError: Cannot read property 'repositories' of null

### ISSUE THREAD

**Issue by xgqfrms** [yoshi389111/github-profile-3d-contrib#43]
**Describe the bug**

```code
TypeError: Cannot read property 'repositories' of null
    at Object.fetchData (/home/runner/work/_actions/yoshi389111/github-profile-3d-contrib/0.[7](https://github.com/xgqfrms/xgqfrms/actions/runs/3360733405/jobs/5570284550#step:3:8).0/dist/index.js:1430:31)
Error: error
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.main (/home/runner/work/_actions/yoshi3[8](https://github.com/xgqfrms/xgqfrms/actions/runs/3360733405/jobs/5570284550#step:3:9)[9](https://github.com/xgqfrms/xgqfrms/actions/runs/3360733405/jobs/5570284550#step:3:10)111/github-profile-3d-contrib/0.7.0/dist/index.js:1507:26)

```

https://github.com/xgqfrms/xgqfrms/actions/runs/3360733405

**To Reproduce**

**Expected behavior**

fix this error, and success build.

**Screenshots**

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7291672/198994475-56b8cfec-1b25-489e-8cc3-48e29c1a660d.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [Version 108.0.5359.19 (Official Build) dev (x86_64)]

**Additional context**

workflow.yml

```yml
name: GitHub-Profile-3D-Contrib
on:
  schedule: [{cron: "59 23 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@latest
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250

      - name: Print env ❓
        run: env | sort
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email xgqfrms@xgqfrms.xyz
          git add -A .
          git commit -m "feat: update GitHub 3D Profile"
          git push

```

**Comment by xgqfrms** [comment]
https://github.com/xgqfrms/xgqfrms/actions/runs/3360733405/workflow

```yml
name: GitHub-Profile-3D-Contrib
on:
  schedule: [{cron: "59 23 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@latest
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250

      - name: Print env ❓
        run: env | sort
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email xgqfrms@xgqfrms.xyz
          git add -A .
          git commit -m "feat: update GitHub 3D Profile"
          git push

```
