### ISSUE TITLE
[Feature] Add border/stroke

### ISSUE THREAD

**Issue by Drjacky** [yoshi389111/github-profile-3d-contrib#45]
Is it possible to add the border/stroke option (be able to set its colour - and define its corner radius as well)?

Like:
<img width="108" alt="Screenshot 2022-11-06 at 16 30 40" src="https://user-images.githubusercontent.com/2296754/200182630-47f06134-dd5b-43b1-9454-4bff60a5ced0.png">

**Comment by DennisFeldbusch** [comment]
Would like that, too!

**Comment by yoshi389111** [comment]
Hello, thank you for your request.

However, I think that there are many variations of borders that you want to add, so instead of adding border options to github-profile-3d-contrib, I would like to handle it with a small script.

Create a python script like the one below in your profile repository.

```python
#!/usr/bin/env python3

import sys
import xml.etree.ElementTree as ET

def main():
    if len(sys.argv) != 3:
        raise Error('usage: {} INPUT_SVG_FILE OUTPUT_FILE'.format(sys.argv[0]))
    tree = ET.parse(sys.argv[1])
    ET.register_namespace('', 'http://www.w3.org/2000/svg')
    root = tree.getroot()
    bg = root.find('{http://www.w3.org/2000/svg}rect')

    bg.attrib["stroke"] = "white"
    bg.attrib["stroke-width"] = "1"
    bg.attrib["rx"] = "10"
    bg.attrib["ry"] = "10"

    tree.write(sys.argv[2], encoding='UTF-8')

if __name__ == '__main__':
    main()
```

Modify the following contents to your liking.

* `bg.attrib["stroke"] = "white"` - color of border
* `bg.attrib["stroke-width"] = "1"` - width of border
* `bg.attrib["rx"] = "10"` - corner radius X
* `bg.attrib["ry"] = "10"` - corner radius Y

Create a python script like the one below in your profile repository.

For example, let's say you made it with the name `bin/change-border.py` .

Please modify the `.github/workflows/profile-3d.yml` file as follows.

```diff
  name: GitHub-Profile-3D-Contrib
  
  on:
    schedule: # 03:00 JST == 18:00 UTC
      - cron: "0 18 * * *"
    workflow_dispatch:
  
  jobs:
    build:
      runs-on: ubuntu-latest
      name: generate-github-profile-3d-contrib
      steps:
        - uses: actions/checkout@v3
        - uses: yoshi389111/github-profile-3d-contrib@0.7.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
+       - uses: actions/setup-python@v4
+         with:
+           python-version: '3.10' 
+       - run: python ./bin/change-border.py profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/profile-night-rainbow-with-border.svg
        - name: Commit & Push
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A .
            git commit -m "generated"
            git push
```

The first argument of the script is the input file and the second is the output file.

**Comment by Drjacky** [comment]
It doesn't generate the profile-custom-evergreen-with-border

My readme:
```
![](./profile-3d-contrib/profile-custom-evergreen-with-border.svg)
```

My change-border-.py:
```
#!/usr/bin/env python3

import sys
import xml.etree.ElementTree as ET

def main():
    if len(sys.argv) != 3:
        raise Error('usage: {} INPUT_SVG_FILE OUTPUT_FILE'.format(sys.argv[0]))
    tree = ET.parse(sys.argv[1])
    ET.register_namespace('', 'http://www.w3.org/2000/svg')
    root = tree.getroot()
    bg = root.find('{http://www.w3.org/2000/svg}rect')

    bg.attrib["stroke"] = "white"
    bg.attrib["stroke-width"] = "1"
    bg.attrib["rx"] = "10"
    bg.attrib["ry"] = "10"

    tree.write(sys.argv[2], encoding='UTF-8')

if __name__ == '__main__':
    main()
```

My profile-3d.yaml:
```
name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./profile-3d-contrib/ever-green-custom.json
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python ./bin/change-border.py profile-3d-contrib/profile-custom-evergreen.svg profile-3d-contrib/profile-custom-evergreen-with-border.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "3d-contrib generated"
          git push
```

My profile-3d-contrib:
<img width="646" alt="Screenshot 2023-04-27 at 19 24 28" src="https://user-images.githubusercontent.com/2296754/234957280-5e2582be-3121-42ef-a68e-682da2c97156.png">
