### ISSUE TITLE
3D contrib seems not to be working with snake contributions

### ISSUE THREAD

**Issue by LucasColas** [yoshi389111/github-profile-3d-contrib#46]
Hello,
I tried to add your action.
However it doesn't seem to work when there is already snake contributions.

Use [the Github Action snake contributions](https://github.com/Platane/snk).
Create another .yml file containing : 
```
name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
```
Everytime there is no workflow running.
