### ISSUE TITLE
Unsuccessful run

### ISSUE THREAD

**Issue by mthsBelloni** [yoshi389111/github-profile-3d-contrib#51]
Hi!

First of all, I don't know if it is indeed a bug, I believe it is indeed a mistake on my part, but I don't know which one (lol). I'll put the error that occurred here, I hope you can help me 😅. See below:

```
remote: Permission to mthsBelloni/mthsBelloni.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/mthsBelloni/mthsBelloni/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

And here is the code of the "profile-3d.yml" file:

```
name: GitHub-Profile-3D-Contrib

on:
  schedule: # 15:00 BRT == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
```
