### ISSUE TITLE
Cannot read properties of null (reading 'repositories')

### ISSUE THREAD

**Issue by pranavelric** [yoshi389111/github-profile-3d-contrib#55]
**Describe the bug**
I am not sure if it is indeed a bug, I believe it might be a mistake on my part, I hope you can help me 😅. See below:

```

TypeError: Cannot read properties of null (reading 'repositories')
    at Object.fetchData (/home/runner/work/_actions/yoshi389111/github-profile-3d-contrib/0.7.1/dist/index.js:1430:31)
Error: error
    at processTicksAndRejections (node:internal/process/task_queues:9[6](https://github.com/pranavelric/pranavelric/actions/runs/5378419004/jobs/9758190077#step:3:7):5)
    at async Object.main (/home/runner/work/_actions/yoshi389111/github-profile-3d-contrib/0.[7](https://github.com/pranavelric/pranavelric/actions/runs/5378419004/jobs/9758190077#step:3:8).1/dist/index.js:1507:26)
```

**To Reproduce**

**Expected behavior**
Successful build

**Screenshots**
![image](https://github.com/yoshi389111/github-profile-3d-contrib/assets/43497595/8c5998fa-2369-49d7-9ccb-a8cbb4d1d072)

**Desktop (please complete the following information):**
 - OS: [MacOs]
 - Browser [Opera]
 - Version [99.0.4788.65]

**Additional context**
profile-3d.yml :

```

name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email pranavchoudhary500@gmail.com
          git add -A .
          git commit -m "GitHub 3D Profile"
          git push

```
